# Generated by Django 3.0.7 on 2020-06-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('date', models.CharField(max_length=35)),
                ('text', models.CharField(max_length=35)),
            ],
        ),
    ]
