# Generated by Django 3.0.7 on 2020-06-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20200627_0955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Remimder',
            new_name='Reminder',
        ),
    ]
