# Generated by Django 3.0.7 on 2020-06-27 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_reminder_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name']},
        ),
    ]
