# Generated by Django 3.0.7 on 2020-06-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_auto_20200627_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['title']},
        ),
    ]
